CREATE TABLE USER (
  id SERIAL PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  name VARCHAR(50) NOT NULL,
  password VARCHAR(50) NOT NULL,
  token VARCHAR(255)
);

CREATE TABLE ROBOT (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  owner INTEGER REFERENCES USER(id),
  initial_time TIMESTAMP,
  final_time TIMESTAMP
);


CREATE TABLE AREA (
  id SERIAL PRIMARY KEY,
  robot_id INTEGER REFERENCES ROBOT(id),
  height INTEGER NOT NULL,
  width INTEGER NOT NULL
);


